FactoryGirl.define do
  factory :teryt_pna_code, class: 'Teryt::PnaCode' do
    woj "MyString"
    woj_nazwa "MyString"
    pow "MyString"
    pow_nazwa "MyString"
    gmi "MyString"
    gmi_nazwa "MyString"
    nazdod "MyString"
    rodz_gmi "MyString"
    rodz_gmi_nazwa "MyString"
    rm "MyString"
    rm_nazwa "MyString"
    sym "MyString"
    sym_nazwa "MyString"
    sympod "MyString"
    sympod_nazwa "MyString"
    sym_ul "MyString"
    mie_nazwa "MyString"
    uli_nazwa "MyString"
    cecha "MyString"
    nazwa_1 "MyString"
    nazwa_2 "MyString"
    stan_na "2016-03-13"
    teryt "MyString"
    pna "MyString"
    numery "MyString"
    pna_teryt "MyString"    
  end
end
