Metrics/LineLength:
  Max: 120
  # If you want the rule only apply to a specific folder/file
AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/**/*'
